name: API CI

on: [push]

defaults:
  run:
    working-directory: ./

jobs:

  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with: 
          node-version: 14
          cache: 'npm'
      - name: Install dependences
        shell: bash
        run: npm install
      - name: Run linter
        shell: bash
        run: npm run lint

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with: 
          node-version: 14
          cache: 'npm'
      - name: Install dependences
        shell: bash
        run: npm install
      - name: Run unit test
        shell: bash
        run: npm run test

  e2e:
    runs-on: ubuntu-latest
    container:
      image: node:14
    services:
      mongo-e2e:
        image: mongo:4.4
      ports:
        - 27017:27017
      env:
        MONGO_INITDB_ROOT_USERNAME: test
        MONGO_INITDB_ROOT_PASSWORD: test123
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependences
        shell: bash
        run: npm install
      - name: Run e2e test
        shell: bash
        run: npm run test:e2e
        env: 
          MONGO_DB_NAME: demo
          MONGO_URL: mongodb+srv://test:test123@mongo-e2e:27017/?retryWrites=true&w=majority
    

